### ISSUE TITLE
Thumbnail of whole graph and hover with value

### ISSUE THREAD

**Issue by tprochazka** [KoalaPlot/koalaplot-core#94] opened 2024-12-02 00:36 UTC
Functionality like this would be awesome: 

Especially on wasmJS target is important to support different zooming that pinch-to-zoom.
AmCharts has awesome support for it:

https://www.amcharts.com/demos/line-chart-with-scroll-and-zoom/

Als displaying the exact x and y values while moving the mouse over the graph would be awesome.

**Comment by gsteckman** [comment] 2024-12-03 04:34
Zooming and scrolling is supported.

For the mouse tracking feature, I think items #28 and #55 cover that. If you agree please go to those and give them a 👍.

**Comment by tprochazka** [comment] 2024-12-04 22:24
Zooming and scrolling don't work in wasmJS for me (with mouse, I did not try touchpad).
I would expect that the mouse wheel will work there.
It works on Android.

Here is possible to zoom in even by pres and drag by mouse (selecting required area)
https://www.amcharts.com/demos-v4/line-chart-with-scroll-and-zoom-v4/

**Comment by gsteckman** [comment] 2024-12-05 01:08
This was added in #90. Are you using version 0.7.0? Here are some comments from the code on what scrolls/zooms by platform:


### Zooming
 * Desktop: Ctrl/Cmd + mouse wheel/touch scroll (Optional Shift for horizontal scaling)
 *
 * Js/JsWasm: mouse/touch scroll (Optional Shift for horizontal zooming). It doesn't work for mobile devices
 *
 * Android/iOS: standard gesture behavior
 *
 * ### Panning
 * Desktop: mouse wheel/touch scroll (Optional Shift for horizontal panning) or click with movement
 *
 * Js/JsWasm: just a click with a move. It doesn't work for mobile devices
 *
 * Android/iOS: standard gesture behavior
 *
 * Ctrl/Cmd are not used in Js/JsWasm because they are reserved for native scaling in browsers

**Comment by gsteckman** [comment] 2024-12-25 21:09
Duplicate of #28, #55, #90

**Closed by gsteckman** 2024-12-25 21:09 UTC
