### ISSUE TITLE
Crash: Pie Chart with 5 values, last one is zero

### ISSUE THREAD

**Issue by Wavesonics** [KoalaPlot/koalaplot-core#20] opened 2023-09-02 19:20 UTC
The fix was to add `0.01f` to every value so that none of them were zero 🤦

**Comment by gsteckman** [comment] 2023-09-03 20:31
I'm not able to reproduce this. What version are you using? Can you share a stack trace?

**Comment by gsteckman** [comment] 2023-12-02 17:14
Closing - can't reproduce.

**Closed by gsteckman** 2023-12-02 17:14 UTC
